--List of notaries who worked the most hours in a specific month and year
SELECT U.first_name, U.last_name, SUM(TIMESTAMPDIFF(HOUR, A.start_time, A.end_time)) AS total_hours_worked
FROM User U
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Client C ON A.client_id = C.client_id
WHERE U.role = 'Notary' AND EXTRACT(MONTH FROM A.date) = 4 AND EXTRACT(YEAR FROM A.date) = 2023
GROUP BY U.user_id
ORDER BY total_hours_worked DESC;

--Notaries with the highest number of notarized documents in a specific month and year
SELECT U.first_name, U.last_name, COUNT(D.document_id) AS total_documents
FROM User U
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Client C ON A.client_id = C.client_id
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND EXTRACT(MONTH FROM A.date) = 4 AND EXTRACT(YEAR FROM A.date) = 2023
GROUP BY U.user_id
ORDER BY total_documents DESC;

--List of notaries who have notarized documents for a specific service and have an average rating above a certain threshold
SELECT U.first_name, U.last_name, AVG(R.rating) AS average_rating
FROM User U
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Review R ON A.appointment_id = R.appointment_id
JOIN Service S ON D.document_type = S.service_name
WHERE U.role = 'Notary' AND S.service_name = 'Some Service Name' AND D.status = 'Notarized'
GROUP BY U.user_id
HAVING AVG(R.rating) > 4;

--List of notaries who have notarized documents for clients from a specific city
SELECT DISTINCT U.first_name, U.last_name
FROM User U
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Client C ON A.client_id = C.client_id
JOIN Address Addr ON C.address_id = Addr.address_id
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND Addr.city = 'Some City';

--Total number of notarized documents per service for a specific month and year
SELECT S.service_name, COUNT(D.document_id) AS total_documents
FROM Service S
JOIN Document D ON S.service_name = D.document_type
JOIN Appointment A ON D.appointment_id = A.appointment_id
JOIN User U ON A.user_id = U.user_id
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND EXTRACT(MONTH FROM A.date) = 4 AND EXTRACT(YEAR FROM A.date) = 2023
GROUP BY S.service_name;

--Total revenue generated by each department for a specific month and year
SELECT Dep.department_name, SUM(P.amount) AS total_revenue
FROM Department Dep
JOIN User U ON Dep.department_id = U.department_id
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Payment P ON D.document_id = P.document_id
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND EXTRACT(MONTH FROM P.date) = 4 AND EXTRACT(YEAR FROM P.date) = 2023
GROUP BY Dep.department_name;

--List of notaries who have notarized documents for clients with a specific occupation
SELECT DISTINCT U.first_name, U.last_name
FROM User U
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Client C ON A.client_id = C.client_id
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND C.occupation = 'Some Occupation';

--List of notaries who have notarized documents for clients who live in a specific zip code
SELECT DISTINCT U.first_name, U.last_name
FROM User U
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Client C ON A.client_id = C.client_id
JOIN Address Addr ON C.address_id = Addr.address_id
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND Addr.zip = 'Some Zip Code';

--List of clients who have used notary services more than a certain number of times, grouped by occupation
SELECT C.occupation, C.first_name, C.last_name, COUNT(A.appointment_id) AS total_appointments
FROM Client C
JOIN Appointment A ON C.client_id = A.client_id
JOIN User U ON A.user_id = U.user_id
WHERE U.role = 'Notary'
GROUP BY C.client_id
HAVING total_appointments > 5
ORDER BY C.occupation;

--List of notaries who have notarized documents for clients who live in specific neighborhoods and have an average rating above a certain threshold
SELECT U.first_name, U.last_name, AVG(R.rating) AS average_rating
FROM User U
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Review R ON A.appointment_id = R.appointment_id
JOIN Client C ON A.client_id = C.client_id
JOIN Address Addr ON C.address_id = Addr.address_id
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND Addr.neighborhood IN ('Neighborhood 1', 'Neighborhood 2', 'Neighborhood 3')
GROUP BY U.user_id
HAVING AVG(R.rating) > 4;

--Notaries with the highest number of notarized documents for a specific service, grouped by department
SELECT Dep.department_name, U.first_name, U.last_name, COUNT(D.document_id) AS total_documents
FROM Department Dep
JOIN User U ON Dep.department_id = U.department_id
JOIN Appointment A ON U.user_id = A.user_id
JOIN Document D ON A.appointment_id = D.appointment_id
JOIN Service S ON D.document_type = S.service_name
WHERE U.role = 'Notary' AND D.status = 'Notarized' AND S.service_name = 'Some Service Name'
GROUP BY Dep.department_name, U.user_id
ORDER BY total_documents DESC;
